version: '3'
networks:
  app-bridge-network:
    driver: bridge
volumes:
  nginx-app-volume:
services:
  nginx-tls:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - COUNTRY=IN
        - STATE=Tamil Nadu
        - LOCATION=Ooty
        - ORGANIZATION=DevOps Org
        - COMMON_NAME=nginx.devops.org
    volumes:
      - nginx-app-volume:/usr/share/nginx/html
    networks:
      - app-bridge-network
    ports:
      - "80:80"
      - "443:443"